language: node_js
node_js:
    - "node"
before_script:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
script:
    - "karma start --browsers Firefox --single-run"
after_success:
    - bash deploy.sh